objects/Product2/fields/Stock__c.field-meta.xml
<CustomField>
    <fullName>Stock__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The quantity of products, what is currently present in our shop</description>
    <label>Stock</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/PurchaseOrder__c/PurchaseOrder__c.object-meta.xml
<CustomObject>
    <label>Purchase Order</label>
    <nameField>
        <label>Purchase Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PurchaseOrder__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/PurchaseOrderLineItem__c/PurchaseOrderLineItem__c.object-meta.xml
<CustomObject>
    <label>Purchase Order Line</label>
    <nameField>
        <label>Purchase Order Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PurchaseOrderLineItem__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Purchase_Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/PurchaseOrderLineItem__c/fields/Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order__c</fullName>
    <label>Purchase Order</label>
    <referenceTo>PurchaseOrder__c</referenceTo>
    <relationshipLabel>Purchase Order Lines</relationshipLabel>
    <relationshipName>PurchaseOrderLineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

classes/PurchaseOrderSelector.cls
public with sharing class PurchaseOrderSelector {

    public static List<PurchaseOrder__c> selectPurchaseOrders(Set<String> Ids_PurchaseOrders) {
        List<PurchaseOrder__c> purchaseOrders = [SELECT Id,  (SELECT Id, Product__c, Quantity__c FROM PurchaseOrderLineItems__r)
                                                 FROM PurchaseOrder__c
                                                 WHERE Id IN :Ids_PurchaseOrders];
        return purchaseOrders;
    }

    public static List<PurchaseOrder__c> draftPurchaseOrders() {
        List<PurchaseOrder__c> purchaseOrders = [SELECT Id, Name, CreatedDate, (SELECT Id, Product__c, Quantity__c FROM PurchaseOrderLineItems__r)
        FROM PurchaseOrder__c
        WHERE Status__c = 'Draft'];
        return purchaseOrders;
    }

    public static List<PurchaseOrderLineItem__c> selectPurchaseOrderLines(Set<String> Ids_PurchaseOrders) {
        List<PurchaseOrderLineItem__c> purchaseOrderLines = [SELECT Id, Product__c, Quantity__c
                                                             FROM PurchaseOrderLineItem__c
                                                             WHERE Purchase_Order__c IN :Ids_PurchaseOrders];
        return purchaseOrderLines;
    }

    public static List<Product2> selectProducts(Set<String> Ids_Products) {
        List<Product2> products = [SELECT Id, Stock__c
                                   FROM Product2
                                   WHERE Id IN :Ids_Products];
        return products;
    }

}