objects/Product2/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Vendor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Vendor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/PurchaseOrder__c/PurchaseOrder__c.object-meta.xml
<CustomObject>
    <label>Purchase Order</label>
    <nameField>
        <label>Purchase Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PurchaseOrder__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/PurchaseOrder__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Vendor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Vendor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/PurchaseOrderLineItem__c/PurchaseOrderLineItem__c.object-meta.xml
<CustomObject>
    <label>Purchase Order Line</label>
    <nameField>
        <label>Purchase Order Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PurchaseOrderLineItem__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Purchase_Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/PurchaseOrderLineItem__c/fields/Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order__c</fullName>
    <label>Purchase Order</label>
    <referenceTo>PurchaseOrder__c</referenceTo>
    <relationshipLabel>Purchase Order Lines</relationshipLabel>
    <relationshipName>PurchaseOrderLineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

classes/PurchaseOrderController.cls
public with sharing class PurchaseOrderController {

    @AuraEnabled
    public static String addOrder(Id accountId, String name_order) {
        PurchaseOrder__c po = new PurchaseOrder__c(Vendor__c = accountId, Name = name_order, Status__c = 'Draft');
        insert po;
        return po.Id;
    }

    @AuraEnabled(Cacheable=true)
    public static List<Product2> getProducts() {
        return ProductSelector.selectProduct2s();
    }

    @AuraEnabled
    public static void addLines(Id accountId, String name_order, String j_items) {
        Map<String, Map<Integer, Decimal>> items = (Map<String, Map<Integer, Decimal>>) JSON.deserialize(j_items, Map<String, Map<Integer, Decimal>>.class);

        Id orderId = null;
        orderId = addOrder(accountId, name_order);

        if (orderId != null) {
            Map<Id, Decimal> prices = new Map<Id, Decimal>();
            Map<Id, String> names = new Map<Id, String>();
            List<PurchaseOrderLineItem__c> lineItems = new List<PurchaseOrderLineItem__c>();
            Set<String> Ids = new Set<String> (items.keySet());
            List<PricebookEntry> products = ProductSelector.selectProductsPrice(Ids);

            if (!products.isEmpty()) {
                for (PricebookEntry p : products) {
                    prices.put(p.Product2.Id, p.UnitPrice);
                    names.put(p.Product2.Id, p.Product2.Name);
                }
            }
            if (!prices.isEmpty() && !names.isEmpty()) {
                Map<Integer, Decimal> items2 = new Map<Integer, Decimal>();
                for (Id id : Ids) {
                    items2.putAll(items.get(id));
                    for (Integer key : items2.keySet()) {
                        lineItems.add(new PurchaseOrderLineItem__c(Purchase_Order__c = orderId, Product__c = id, Name = names.get(id),
                                Quantity__c = items2.get(key), Unit_Price__c = prices.get(id)));
                    }
                    items2.clear();

                }

            }

            if (!lineItems.isEmpty()) {
                insert lineItems;
            }
        }
    }

}